services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./envs/db.env
    volumes:
      - data:/var/lib/postgresql/data

  monorepo:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: monorepo
    ports:
      - "5555:5555"
      - "9000:9000"
      - "9050:9050"
    env_file:
      - ./envs/be.env
      - ./envs/fe.env
    volumes:
      - ./apps/be/src:/app/apps/be/src
      - ./apps/fe/src:/app/apps/fe/src
    depends_on:
      - db
      
volumes:
  data: