import type { Metadata } from "next";

import "@xstory/tailwind-config/globals.css";

import { ThemeProvider, ThemeToggle } from "@xstory/ui/theme";
import TRPCProvider from "#fe/providers/TRPCProvider";
import Header from "#fe/components/layouts/Header";
import Main from "#fe/components/layouts/Main";
import Footer from "#fe/components/layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head></head>
      <body className="m-4 flex h-[calc(100vh-32px)] flex-col rounded-lg border">
        <div className="flex flex-1 border-b">
          <Header />
          <Main>
            <TRPCProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                <ThemeToggle />
                {children}
              </ThemeProvider>
            </TRPCProvider>
          </Main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
